services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - jean_network
    deploy:
      resources:
        limits:
          memory: 1G

  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - LOG_LEVEL=INFO
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - DEV_MODE=true
    volumes:
      - ./backend:/app
      - /app/.venv
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - jean_network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - jean_network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M

  # Redis for caching/rate-limiting (optional but recommended for production)
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - jean_network
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  jean_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 